#!/bin/bash

source ./helper

SUPPORTED_OPTIONS="h?r:t:"
while getopts "h?r:t:" opt; do
	case "$opt" in
	h|\?)
		echo "supported options:"
		echo "  -h, -?"
		echo "    show help"
		echo "  -r JOB"
		echo "    resume from the given job (optional)"
		echo "  -t TARGET_DIR"
		echo "    write to the given target folder"
		exit 1
	;;
	r)
		RESUME_FROM=$OPTARG
	;;
	t)
		TARGET_DIR=$OPTARG
	;;
	esac
done
shift $((OPTIND-1))

[ -z "$TARGET_DIR" ] && die "target dir must be set: -t TARGET_DIR"

DIR=$(dirname $(realpath $0))
JOB_DIR=$DIR/job
JOBS=$(ls $JOB_DIR | sort)

processJob() {
	JOB=$1
	$JOB_DIR/$JOB
}

checkElevated()
{
	at > /dev/null
	[ $? -ne 0 ] && die "$0 requires elevation (Run As Administrator)"
}

checkElevated
checkTargetDir $TARGET_DIR
echo "processing $(echo $JOBS | wc -w) jobs"
prepareStagingFolder
for JOB in $JOBS
do
	if [ ! -z "$RESUME_FROM" ];
	then
		if [ "$JOB" == "$RESUME_FROM" ];
		then
			RESUME_FROM_DONE="yes"
		fi
	fi
	if [ -z "$RESUME_FROM" ] || [ "$RESUME_FROM_DONE" ];
	then
		echo -e "\tprocessing $JOB"
		processJob $JOB | sed 's/^/\t\t/'
	
		[ ${PIPESTATUS[0]} -eq "0" ] || die "terminating now"
	else
		echo -e "\tskipping $JOB"
	fi
done
copyToTargetFolder $TARGET_DIR
removeStagingFolder
echo "all done"
