#!/bin/bash

# function that prints exit message and exits script with status 1
die()
{
	echo "failed to do backup: $@"
	exit 1
}

# STAGING_FOLDER_IDEMPOTENT=set

prepareStagingFolder()
{
	echo "preparing staging folder: $(stagingFolder)"
	[ -z $STAGING_FOLDER_IDEMPOTENT ] && [ -e $(stagingFolder) ] && die "staging folder already exists: $(stagingFolder)"
	mkdir --parents $(stagingFolder)
}

stagingFolder()
{
	echo "/tmp/backuptool_staging"
}

listStagingFolder()
{
	echo "contents of staging folder: $(du -sh $(stagingFolder) | awk '{print $1;}')"
	du -sh $(stagingFolder)/* | sed 's/^/\t/'
}

removeStagingFolder()
{
	listStagingFolder

	if [ -z $STAGING_FOLDER_IDEMPOTENT ]
	then
		echo "removing staging folder: $(stagingFolder)"
		[ ! -e $(stagingFolder) ] && die "staging folder does not exist: $(stagingFolder)"
		rm -rf $(stagingFolder) || die "problem removing staging folder: $(stagingFolder)"
	fi
}

userProfile()
{
	cygpath $USERPROFILE
}

applicationData()
{
	cygpath $APPDATA
}

packageFolder()
{
	SIMPLE_NAME=$1
	FOLDER_NAME=$2
	echo "packaging up folder: $FOLDER_NAME"
	pushd $FOLDER_NAME
	tar --absolute-names -zcf $(stagingFolder)/$SIMPLE_NAME.tar.gz * || die "problem packaging as tar: $FOLDER_NAME"
	popd
}

exportRegistryKey()
{
	SIMPLE_NAME=$1
	REGISTRY_KEY_NAME=$2
	echo "exporting registry key: $REGISTRY_KEY_NAME"
	regedit /e $(cygpath --windows $(stagingFolder)/$SIMPLE_NAME.reg) $REGISTRY_KEY_NAME
}

checkTargetDir()
{
	local TARGET_DIR=$1
	[ -z "$TARGET_DIR" ] && die "target folder not set"
	if [ -e "$TARGET_DIR" ];
	then
		[ "$(ls -A $TARGET_DIR)" ] && die "target folder is not empty"
	fi
}

copyToTargetFolder()
{
	local TARGET_DIR=$1
	mkdir --parents $TARGET_DIR || die "cannot create target folder"
	cp -rf $(stagingFolder)/* $TARGET_DIR/ || die "cannot copy to target folder"
}
